### PR TITLE
Improve the Sort by name text in drop-down

### PR DESCRIPTION
**Pull request by chalov-anton**
### Description (*)

This PR provides a small improvement for Sort by name text to be similar to [UI Prototype](https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/0455ed2c-b377-4927-98df-657671cd58f8/Gallery-sort-order)

### Fixed Issues (if relevant)

Before
before

After
after

### Manual testing scenarios (*)
Open Media Gallery
Click **Sort by** drop-down

### CODE REVIEW

**Review by coderimus — DISMISSED** [review]
Hi @chalov-anton ! Looks good 👍

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA PAssed

**Pull request merged**
