### PR TITLE
Add support of PNG IPTC reading && writing to MediaGalleryMetadata module implementation

### LINKED ISSUE #1553: Add support of PNG IPTC reading to MediaGalleryMetadata module implementation
Add support of GIF XMP readingto MediaGalleryMetadat module implementation.

Technical Design:
https://github.com/magento/adobe-stock-integration/wiki/Technical-Design:-Images-metadata-processing

What needs to be done:
 - Introduce `Magento\MediaGalleryMetadata\Model\Png\Segment\IptcReader`(see examples of implementation in Png and Jpeg namespaces)
 - Add the png image containing only IPTC data to `Magento\MediaGalleryMetadata\Test\Integration\Model\ExtractMetadataTest` integration test
 - Cover the implementation with `Magento\MediaGalleryMetadata\Test\Integration\Model\AddIptcMetadataTest` integration test (should be the same as `Magento\MediaGalleryMetadata\Test\Integration\Model\AddIptcMetadataTest` however the Magento\MediaGalleryMetadataApi\Api\AddMetadataInterface instance used should be configured to use only Iptc writer)

### LINKED ISSUE #1669: Add support of PNG IPTC writing to MediaGalleryMetadata module implementation
Add support of PNG IPTC writing to MediaGalleryMetadat module implementation.

Technical Design:
https://github.com/magento/adobe-stock-integration/wiki/Technical-Design:-Images-metadata-processing

What needs to be done:
 - Introduce `Magento\MediaGalleryMetadata\Model\Png\Segment\IptcWriter`(see examples of implementation in Png and Jpeg namespaces)
 - Add the png image containing only IPTC data to `Magento\MediaGalleryMetadata\Test\Integration\Model\ExtractMetadataTest` integration test
 - Cover the implementation with `Magento\MediaGalleryMetadata\Test\Integration\Model\AddIptcMetadataTest` integration test (should be the same as `Magento\MediaGalleryMetadata\Test\Integration\Model\AddIptcMetadataTest` however the Magento\MediaGalleryMetadataApi\Api\AddMetadataInterface instance used should be configured to use only Iptc writer)

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1553: Add support of PNG IPTC reading to MediaGalleryMetadata module implementation
2. Fixes magento/adobe-stock-integration#1669: Add support of PNG IPTC writing to MediaGalleryMetadata module implementatio

### Manual testing scenarios (*)

1. ...
2. ...

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
