### PR TITLE
fix typo. sentence in error message starts from lower case 

### PR DESCRIPTION
**Pull request by chalov-anton**
### Description (*)

When trying to upload an image that exceeds file size limit, an error message appears. The error message consists of two sentences. The second sentence starts from lower case 

### Fixed Issues (if relevant)

file_name

### Manual testing scenarios (*)

1. Open Media Gallery
2. Click Upload image
3. Select an image sized more than 2MB

### CODE REVIEW

**Review by coderimus — CHANGES_REQUESTED** [review]
Hi @chalov-anton  ! Thank you for the provided fix. Everything looks good. But to proceed with the PR please,  sign the Adobe CLA.

**Comment by chalov-anton** [comment]
> Hi @chalov-anton ! Thank you for the provided fix. Everything looks good. But to proceed with the PR please, sign the Adobe CLA.

:heavy_check_mark: Done

**Review by coderimus — DISMISSED** [review]

**Comment by sivaschenko** [comment]
@magento run Functional Tests EE

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento run Functional Tests EE

**Comment by sivaschenko** [comment]
Only inventory MFTF tests failed that are not required currently

**Pull request merged**
