### PR TITLE
Use ImportFileComposite in Adobe Stock

### LINKED ISSUE #1666: Use ImportFileComposite in Adobe Stock
### Technical Details

 - `\Magento\AdobeStockImage\Model\SaveImage::execute` method has to be updated:
`\Magento\MediaGallerySynchronizationApi\Model\ImportFileComposite::execute($destinationPath)` should be called after
`$this->saveMediaGalleryAsset->execute($document, $destinationPath);`
 - `resizeFile` call should be removed from `\Magento\AdobeStockImage\Model\Storage\Save::execute`
 - `setDescriptionFiled` function should be removed from `\Magento\AdobeStockImage\Model\SaveMediaGalleryAsset`

### Testing instructions:

Verify the initial asset details and details editing (pay attention to description, title, keywords, presence of generated thumbnail) for:
 - adobe stock preview image
 - licensed adobe stock image
 - preview adobe stock image that is licensed afterwards

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1666:Use ImportFileComposite in Adobe Stock 
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by sivaschenko — DISMISSED** [review]

**Comment by sivaschenko** [comment]
```
FILE: ...html/app/code/Magento/MediaGalleryUi/Plugin/CreateThumbnails.php
----------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 33 | ERROR | [x] @param is not found for one or more params in
    |       |     method annotation
 33 | ERROR | [x] $filesystem parameter is missing in method
    |       |     annotation
 43 | ERROR | [x] $path parameter is missing in method arguments
    |       |     signature
 46 | ERROR | [x] $paths parameter is missing in method annotation
----------------------------------------------------------------------
PHPCBF CAN FIX THE 4 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

**Comment by sivaschenko** [comment]
@magento run all tests

**Pull request merged**
