### PR TITLE
The "Undiscovered" filter is presented in Sort by drop-down list, not as a separate filter

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#807: The "Undiscovered" filter is presented in Sort by drop-down list, not as a separate filter

### Manual testing scenarios (*)

1. ...
2. ...

### CODE REVIEW

**Comment by sivaschenko** [comment]
Hi @Nazar65 thanks for the pull request. Looks like the undiscovered filter is conflicting with sorting: sorting does not work if the undiscovered filter is applied.

Looks like we cannot use undiscovered as filter considering the actual Adobe Stock API documentation: https://www.adobe.io/apis/creativecloud/stock/docs.html#!adobe/stock-api-docs/master/docs/api/11-search-reference.md

@chfabbro do you think there is a way to use both `undiscovered` filter and sorting by i.e. `relevance` in the request to Adobe Stock API?

**Comment by chfabbro** [comment]
> @chfabbro do you think there is a way to use both `undiscovered` filter and sorting by i.e. `relevance` in the request to Adobe Stock API?

@sivaschenko They are mutually exclusive, i.e., "either/or". You can _either_ sort by "relevance," or sort by "undiscovered," but not both. Per the docs you quoted:
```
search_parameters[order]
Sort order in which to return found assets. Default is "relevance". String.
Valid strings and their meanings:
  * relevance
How closely it matches your search request, closest matches first.
  * creation
Creation date in descending order (newest first).
  * popularity
In descending order by the number of views by all users.
  * nb_downloads
In descending order by the number of downloads by all users since the asset was added to Adobe Stock.
  * undiscovered
Starting with assets that have not commonly been viewed or downloaded.

**Comment by sivaschenko** [comment]
Yes @chfabbro , we were just concerned that "undiscovered" is a separate filter on stock.adobe.com
image

**Comment by chfabbro** [comment]
@sivaschenko Yes, that UI is new and unfortunately has different functionality from the Stock API. The website does not use the same API, and instead calls directly to the Adobe Search service. Net, changes would need to be made to the Stock API to imitate this functionality, but it is not on the roadmap at this time.

**Comment by sivaschenko** [comment]
Ok, thanks @chfabbro

**Comment by sivaschenko** [comment]
Considering that API does not support this case I am closing both the PR and the issue.

**Pull request closed without merging**
