### PR TITLE
Addressing Discriminatory Language in Technology

### LINKED ISSUE #28622: Addressing Discriminatory Language in Technology
This issue is automatically created based on existing pull request: magento/magento2#28615: Addressing Discriminatory Language in Technology

---------
### Description (*)
**Blacklist** and **Whitelist** has negative and abusive correlations and is considered as racism. Thus, we should immediately replace these with `allow` and `deny` list.

Due to some technical issues, not all occurrences can be replaced yet, but this is a good start to make a world better.

### Actual result (*)

### PR DESCRIPTION
**Pull request by sivaschenko**
### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/28622 Addressing Discriminatory Language in Technology

### Related Pull Requests
https://github.com/magento/magento2/pull/28615

### CODE REVIEW

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by stollr** [comment]
@sivaschenko Can you please explain why "blacklist" is a racist element?

**Comment by sivaschenko** [comment]
@naitsirch I don't know.

This PR was created in response to the changes in https://github.com/magento/magento2/pull/28615

@lbajsarowicz @lenaorobei maybe you have a link to a resource where the word origin is explained?

**Comment by lbajsarowicz** [comment]
@naitsirch Would you mind review the answer from original PR, please?
https://github.com/magento/magento2/pull/28615#issuecomment-641947459

**Pull request merged**
