### PR TITLE
ASI-163: Writing integration test for module AdobeStockClient for client

### PR DESCRIPTION
**Pull request by engcom-Golf**
### Description (*)
Integration test added for module AdobeStockClient.

### Fixed Issues (if relevant)
1. magento/adobe-stock-integration#163: Writing integration test for module AdobeStockClient for client

### Manual testing scenarios (*)
1. Run integration test:
- \Magento\AdobeStockClient\Test\Integration\Model\ClientTest

### CODE REVIEW

**Review by diazwatson — COMMENTED** [review]
@engcom-Golf couple of question regarding this PR.
I have ran the test and noticed that only 60% of the file is covered.

- Are we aim to provide 100% for each file?
- Is it worth to also test the exceptions?

**Comment by sivaschenko** [comment]
I'd agree with @diazwatson Client is the most critical part of the integration, so I'd prefer testing both positive and negative scenarios to cover Client code completely

**Comment by engcom-Golf** [comment]
@sivaschenko @diazwatson Hello. I've covered other cases, you may check it again.

**Comment by diazwatson** [comment]
Hi @engcom-Golf you now reached **77% covered**, nice!

Screenshot 2019-07-17 at 13 19 20

How difficult would be to also include coverage for `testConnection` method and the exception thrown by the `createAttribute` method? I think that would give us 100% coverage for the Client.!

I can see the `testConnection` method has a **_Todo_** note saying we should refactored so maybe things are going to check in the future but even so I think covering this method tests would actually help us to refactor.

**Comment by engcom-Golf** [comment]
@diazwatson Oh, sorry, I have not seen catch in method createAttrbutes, I'll add case for this case.
As for method testConnection - I didn't cover this method because I creating mock for connection, so I see no reason to check data which I added in mock.

**Comment by engcom-Golf** [comment]
@diazwatson You may check it again :)

**Review by diazwatson — APPROVED** [review]

**Pull request merged**
