### PR TITLE
[WIP] Possible MFTF test fail scenario discussion #660

### PR DESCRIPTION
**Pull request by drpayyne**
### Description

> **On hold, work in progress**

-  Added a conditional click to skip adding phone number _if_ asked, else, continues with test. 
-  Unable to reproduce as it's not asking me for phone number yet. If anyone can help me obtaining the selector for the _skip_ button, it would be helpful.

### Fixed Issues
-  magento/adobe-stock-integration#660: Possible MFTF test fail scenario discussion

### Manual testing scenarios
-  Run MFTF test by signin in to Adobe Stock account without phone number linked

### Screenshots (for those who aren't able to reproduce it at all)
This is the screen which is shown while signing in if there is no number present in the Adobe Stock account

Screenshot from 2019-11-13 00-29-34

And this is the element ID of the _Not now_ button which the test will be conditionally clicking if it is present

Screenshot from 2019-11-13 00-29-24

### CODE REVIEW

**Comment by sivaschenko** [comment]
@drpayyne can you please update the title of pull request to include a meaningful description and add a `[WIP]` prefix if this pull request is not ready for the review.

(That would be great if you can do this for all your PRs :) )

**Comment by drpayyne** [comment]
Added a selector for click skip button, although the sign in flow isn't working due to inconsistencies in page loads between a normal sign in and when a phone number is asked. Work still in progress to come to a middle ground on page load flows in these two cases.

**Comment by sivaschenko** [comment]
@drpayyne is this pull request ready for review?

**Comment by sivaschenko** [comment]
@filmaj do we need this conditionalClick?

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
