### PR TITLE
20: added sorting to images listing

### PR DESCRIPTION
**Pull request by dmytrokaplin**
### Description (*)
Created sorting functionality for images grid

### Fixed Issues (if relevant)
1. #20 

### Manual testing scenarios (*)
1. Go to Magento 2 admin panel.
2. Go to Content -> Elements -> Pages -> Select Any Page.
3. Go to Content area and click to "Insert Images..." then click to "Search Adobe Stock"
4. Select any option of sorting.
image

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/adobe-stock-integration?pullRequest=134) <br/>All committers have signed the CLA.

**Review by sidolov — DISMISSED** [review]
Hi @jeysmook , the implementation looks good! Just one more thing that we need to fix - place sort control in place according to the mockups. You may find it on [UI prototype](https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/a4495932-9729-4ca6-9321-d9efbb58c8d7/Stock-Search)

Screen Shot 2019-06-25 at 16 09 24

**Comment by dmytrokaplin** [comment]
Hey guys! @sidolov @sivaschenko 

I moved the sorting component to the pager, but for it, I had to rewrite the toolbar.html template.

**It still needs updating styles.**

image

**Comment by sidolov** [comment]
Hi @jeysmook , we will help you with styles, great job!

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
This PR is reviewed and tested. Can be merged as soon as all checks are green
@IvanPletnyov please sign the CLA

**Pull request merged**
