### PR TITLE
Use unique page tittle to avoid selecting wrong page

### LINKED ISSUE #1670: Fix Used In Filters MFTF tests
TBD

### LINKED ISSUE #1677: MFTF stbilization of selecting an asset in media gallery
- Use only ImageUpload3 image for MediaGalleryUi tests
 - Update all media gallery grid item selectors to parametrized selectors based on asset title
 - Use `ImageMetadata.title` title in the tests to select uploaded `ImageUpload3` image

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1670: Fix Used In Filters MFTF tests
2. Fixes magento/adobe-stock-integration#1677: MFTF stbilization of selecting an asset in media gallery

### Manual testing scenarios (*)
Green MFTF tests

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by Nazar65** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by Nazar65** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by Nazar65** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by Nazar65** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by Nazar65** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by Nazar65** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by Nazar65** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by Nazar65** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
