### PR TITLE
Fixed styling for search adobe stock button

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will fix the incorrect button styling for search adobe stock button
### Fixed Issues (if relevant)

N/A

### Screenshot (*)
**Previous**
image
**Now**
image

### CODE REVIEW

**Comment by konarshankar07** [comment]
I think we need to cover this with MFTF test. Any thoughts?

**Review by Nazar65 — CHANGES_REQUESTED** [review]
@konarshankar07  i think the button is correct please look at -> https://github.com/magento/adobe-stock-integration/issues/1192

**Comment by konarshankar07** [comment]
Hello @Nazar65 ....
yes, you are right but I think we need to change the `Search Adobe Stock` button color as per secondary button color because the button need to stand out of other button and easily differentiate between Adobe stock and Media Gallery button. Can you please confim with the UI/UX designer to check? Or can you please link the Adobe XD file here?
Thanks

**Comment by sivaschenko** [comment]
@konarshankar07 the UI mentioned in the issue linked by @Nazar65 is a request by UX designer.

Thanks for the PR, but unfortunately we can't accept it

**Pull request closed without merging**
