### PR TITLE
"Disable" state for "Search Adobe Stock" to prevent error in console

### PR DESCRIPTION
**Pull request by engcom-Golf**
### Description (*)
When you click to fast on "Search Adobe Stock" you have error in console, and broken grid, Because grid element not loaded yet.

DeepinScreenshot_select-area_20190816085742

**After**
DeepinScreenshot_select-area_20190816091031

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)
1  go to cms -> pages -> new page
2. click insert image -> open adobe stock
3. open dev tools console

### CODE REVIEW

**Review by diazwatson — DISMISSED** [review]

**Comment by engcom-Golf** [comment]
Hi @diazwatson i'm still working on this, will provide description soon. please do not merge )

**Comment by engcom-Golf** [comment]
@diazwatson The core problem is that when you to fast click on Adobe Stock Search button then is a error in console,  and styles not applied to the grid, because grid is not loaded in DOM. So i added disabled state for button, when the grid will be initialized then button will be active
DeepinScreenshot_select-area_20190819144011

**Comment by engcom-Golf** [comment]
@diazwatson  i'm done with this PR, now all works correct, button have state  "disable" until grid not loaded.

**Comment by diazwatson** [comment]
Thanks @engcom-Golf I'll review today

**Review by diazwatson — APPROVED** [review]

**Pull request merged**
