### PR TITLE
[1.0-master] Fix flaky AdminAdobeStockLocalizationTest

### PR DESCRIPTION
**Pull request by sivaschenko**
### Fixed Issues (if relevant)

Fixes https://github.com/magento/adobe-stock-integration/issues/1638
Jira https://jira.corp.magento.com/browse/MC-36140

### Manual testing scenarios (*)

https://app.hiptest.com/projects/131313/test-plan/folders/943908/scenarios/3218880

### Additional info

Backport of https://github.com/magento/adobe-stock-integration/pull/1348

### CODE REVIEW

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run Integration Tests, Functional Tests EE, Functional Tests B2B

**Pull request closed without merging**
