### PR TITLE
fix DownloadTest.php local failure

### PR DESCRIPTION
**Pull request by engcom-Echo**
### Description (*)

local run AdobeStockAdminUi/Test/Unit/Controller/Adminhtml/Preview/DownloadTest.php #testExecuteWithException #testExecute causes warnings

### Fixed Issues (if relevant)

No issues created

### Manual testing scenarios (*)

No manual testing required

### CODE REVIEW

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE

**Comment by gabrieldagama** [comment]
@magento import pr to magento-commerce/adobe-stock-integration

**Comment by magento-engcom-team** [comment]
@gabrieldagama the pull request successfully imported.

**Comment by gabrieldagama** [comment]
Merged to 2.4.2 - https://github.com/magento-commerce/adobe-stock-integration/pull/7 - will be merged back soon.

**Pull request closed without merging**
