### PR TITLE
[WIP]: Implemented #8 Expand preview image on thumbnail click  - phase 1

### PR DESCRIPTION
**Pull request by passtet**
### Description (*)

 - Change masonry grid to flexbox
 - Add preview jQuery template as an example

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#8: Expand preview image on thumbnail click

### Manual testing scenarios (*)

1. ...
2. ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/adobe-stock-integration?pullRequest=138) <br/>All committers have signed the CLA.

**Comment by diazwatson** [comment]
Hi @passtet thanks for your PR.

Please look at the following:
- Associate this PR with an issue number
- Remove the commented out code
- Solve the merge conflicts

**Review by diazwatson — CHANGES_REQUESTED** [review]
Remove the commented out code

**Comment by diazwatson** [comment]
I have discussed this with @sidolov today, he is going to continue reviewing this PR

**Comment by passtet** [comment]
This variant dropped ( using component structure instead https://github.com/magento/adobe-stock-integration/pull/221 )

**Pull request closed without merging**
