### PR TITLE
#89: Implement overlay UI component for Masonry grid image 

### PR DESCRIPTION
**Pull request by andriyShch**
- add styles
 - add html

### Fixed Issues (if relevant)

1. https://github.com/magento/adobe-stock-integration/issues/89: Implement overlay UI component for Masonry grid image
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/adobe-stock-integration?pullRequest=140) <br/>All committers have signed the CLA.

**Review by diazwatson — CHANGES_REQUESTED** [review]
Hi @andriyShch thanks for your PR

Please make sure you accept and sign the [licence/cla](https://cla.dev.magento.com/magento/adobe-stock-integration?pullRequest=140) 
Also due to the recent merges into `develop`, your branch has merge conflicts, in 
```
AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
```

Could you please have a look?

Thanks

**Comment by andriyShch** [comment]
signed
merged

**Comment by diazwatson** [comment]
Hi @andriyShch 
Thanks for signing the license and fixing the conflict.

How can I see the overlay for the masonry grid image component?
Is this a work in progress?

**Comment by andriyShch** [comment]
Hi @diazwatson 
I have added overlay on hover with test word "hello!"
To see this - just hover image in Stock Integration grid

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
