### PR TITLE
#149 Move conf back to system section

### PR DESCRIPTION
**Pull request by diazwatson**
#149 

### Preconditions (*)

1. Checkout `develop` branch

### Steps to reproduce (*)

1. Go to Stores -> Configuration -> Advanced -> System

### Expected result (*)

Screenshot 2019-07-03 at 11 16 58

### Actual result (*)

Screenshot 2019-07-03 at 10 53 33

### CODE REVIEW

**Review by vpodorozh — CHANGES_REQUESTED** [review]
Hi @diazwatson - it was moved outside the `system` section in order to add ACL, check this issue #93  .
Why should we move it back to `system` section?
Thx!

**Comment by diazwatson** [comment]
Hi @vpodorozh you are right that is what issue #93 tells to do, although issue #29 also establish that the  Adobe Stock Integration configuration options should go inside Store-Configuration-Advanced-System.

I think we need @sidolov for clarification

**Comment by sivaschenko** [comment]
That's correct, thanks @diazwatson according to requirements the configuration should be located in the system section, I missed this point.

As there is no way to specify ACL for a system configuration group we'll have to use `Magento_Config::config_system`. So looks like `Magento_AdobeStockAsset::config` should be removed.

**Review by sivaschenko — APPROVED** [review]

**Comment by diazwatson** [comment]
@sidolov thanks for clarifying this.

**Pull request merged**
