### PR TITLE
magento/adobe-stock-integration#1182: PHP 7.4 support

### LINKED ISSUE #1182: PHP 7.4 support
- add PHP 7.4 compatibility
- remove 7.1 and 7.2 compatibility
- keep 7.3 compatibility
- make code and tests comply with this change
- tests should be compatible with PHPUnit 9

### PR DESCRIPTION
**Pull request by lenaorobei**
### Fixed Issues (if relevant)

Closes magento/adobe-stock-integration#1182

### Manual testing scenarios (*)

1. ...
2. ...

### CODE REVIEW

**Comment by lenaorobei** [comment]
AUR build - https://m2build-ur.devops.magento.com/view/all/job/All-User-Requested-Tests/32176/

**Comment by sivaschenko** [comment]
https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/32190/

**Comment by sivaschenko** [comment]
https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/32193/

**Comment by sivaschenko** [comment]
Without Inventory: https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/32194/

**Comment by lenaorobei** [comment]
Closed in favor of https://github.com/magento/adobe-stock-integration/pull/1321 that uses correct branch name.

**Pull request closed without merging**
