### PR TITLE
Replacing AdminOpenMediaGalleryForPageNoEditorActionGroup on mftf tests

### PR DESCRIPTION
**Pull request by gabrieldagama**
### Description (*)
Replacing AdminOpenMediaGalleryForPageNoEditorActionGroup with:
```
<actionGroup ref="AdminOpenCreateNewCMSPageActionGroup" stepKey="openNewPage"/>
<actionGroup ref="AdminOpenMediaGalleryFromPageNoEditorActionGroup" stepKey="openMediaGalleryForPage"/>
```
or
```
<actionGroup ref="AdminOpenStandaloneMediaGalleryActionGroup" stepKey="openMediaGallery"/>
```

### CODE REVIEW

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
