### PR TITLE
Cover case with non existing folder when apllying path filter

### LINKED ISSUE #1362: The Directory filter is applied for non existing folder in Enhanced Media Gallery if Delete a folder from NOT Enhanced Media Gallery
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Go to _Stores - Configuration - Advanced -System - Enhanced Media Gallery_ and select **Enabled - No**
enabled_no

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. **Create Folder**, name it "Unlicensed" for example 
3. Select the previously created folder from the folder tree, so that the _Directory_ filter is applied
4. Go to _Content - Pages_ click **Add New Page**
5. Expand _Content_ click **Show / Hide Editor** - **Insert Image...**
6. **Delete** the previously created folder
7. Go to **Content - Media Gallery** again

### Expected result (*)
The _Directory_ filter is not applied

### Actual result (*)
The _Directory_ filter is applied for the non-existing folder
directory_applied_deleted

### Note
- does NOT cause any error in dev console or issues with saving or uploading images

### PR DESCRIPTION
**Pull request by Nazar65**
### Description (*)

DEPEND ON https://github.com/magento/adobe-stock-integration/pull/1350
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1362: The Directory filter is applied for non existing folder in Enhanced Media Gallery if Delete a folder from NOT Enhanced Media Gallery
2. ...

### Manual testing scenarios (*)
1. Go to **Content - Media Gallery**
2. **Create Folder**, name it "Unlicensed" for example 
3. Select the previously created folder from the folder tree, so that the _Directory_ filter is applied
4. Go to _Content - Pages_ click **Add New Page**
5. Expand _Content_ click **Show / Hide Editor** - **Insert Image...**
6. **Delete** the previously created folder
7. Go to **Content - Media Gallery** again

### Expected result (*)
The _Directory_ filter is not applied

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi @Nazar65 , since this depends on #1350, I would recommend merging that PR here, the implementation of the function checkChipFiltersState has been changed a lot on #1350

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
I'm closing this one, as changes will be migrated to #1350

**Pull request closed without merging**
