### PR TITLE
Use custom services to save entities to the database instead of resource models

### PR DESCRIPTION
**Pull request by engcom-Golf**
### Description (*)
Use custom services to save entities to the database instead of resource models.

Uses resource services for data storage manipulation. Also, save  action provided as a multiply items save process. 
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#293: Use custom services to save entities to the database instead of resource models

### Manual testing scenarios (*)
1.Try to save Preview image.

### CODE REVIEW

**Comment by coderimus** [comment]
@engcom-Golf @sidolov @sivaschenko @okorshenko I think that this pr is dependent on [#330 the issue about delete some columns from asset table](https://github.com/magento/adobe-stock-integration/issues/330) Maybe we should deliver it first and then based on the result update provided implementation in this pr?

**Comment by sivaschenko** [comment]
@engcom-Golf @Nazar65 @coderimus I think we should remove database columns first and then adjust this PR to avoid the need to create 3rd PR to adjust the resource models to new DB schema

**Comment by coderimus** [comment]
@Nazar65 @engcom-Golf @sivaschenko 
Ok, cool. I will provide requested data base changes with code adjustments in the nearest 2 days.

**Comment by engcom-Golf** [comment]
@coderimus @sivaschenko well i'm updated PR to the latest changes.

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
