### PR TITLE
Use thumbnail versions of images for displaying in the media gallery …

### LINKED ISSUE #1085: Use thumbnail versions of images for displaying in the media gallery grid
### Preconditions (*)
Have large images saved in the media gallery
Install Magento 2.4-x with Adobe Stock Integration 1.1-x

### Steps to reproduce (*)
1. Login to Admin Palel
2. Open Media Gallery i.e.:
   - From Admin go to **Content** - **Pages**, click **Add New Page**)
   - Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**

### Actual results (*)

Full-size images are used in the grid

### Expected result (*)

Thumbnails should be used in the grid, full-size images should be used for image details slide panel

### PR DESCRIPTION
**Pull request by Nazar65**
…grid

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1085: Use thumbnail versions of images for displaying in the media gallery grid
2. ...

### Manual testing scenarios (*)
1. Login to Admin Palel
2. Open Media Gallery i.e.:
   - From Admin go to **Content** - **Pages**, click **Add New Page**)

**Thumbnails used in the grid, full-size images  used for image details slide panel**

### CODE REVIEW

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by coderimus** [comment]
@magento run Sample Data Tests EE

**Comment by coderimus** [comment]
@magento run all tests

**Review by coderimus — CHANGES_REQUESTED** [review]
Hi @Nazar65 ! Thank you for the provided fix 👍  Please, check the static test report. Looks like we need to add the MediaGallerySynchroniztion to the "suggest": section of the composer.json to cover soft dependency.

**Review by coderimus — DISMISSED** [review]
@Nazar65  thanks for the updates. We can move it to the acceptance test right after the test passed. 👍

**Comment by coderimus** [comment]
Failed `Functional Tests B2B ` doesn't relate to the provided changes in the PR.

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

**Review by chalov-anton — CHANGES_REQUESTED** [review]
:x: QA Failed 

WYSIWYG adds the thumbnail, not the actual image
wysiwyg_2020-04-30

Works fine via **Insert image**

**Comment by Nazar65** [comment]
:heavy_check_mark: Fixed

**Review by coderimus — APPROVED** [review]

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA PAssed

**Comment by sivaschenko** [comment]
Merged to 2.0.0-develop

**Pull request closed without merging**
