### PR TITLE
Bugfixes and mftf coverage

### PR DESCRIPTION
**Pull request by sivaschenko**
Bugfixes and mftf coverage

### CODE REVIEW

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run Unit Tests,Functional Tests B2B

**Comment by sivaschenko** [comment]
The failed Magento_Paypal tests in the Functional Tests B2B job are not related to the changes

**Comment by ghost** [comment]
Hi @sivaschenko, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+adobe-stock-integration+1426), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request merged**
