### PR TITLE
Fix Name && path sorting, fix Overlay label styles

### LINKED ISSUE #1330: Sorting by Name and by Directory doesn't work in Media Gallery
### Precondition (*)
1. Installed Magento with Adobe Stock Integration
2. Several images Uploaded or Saved from Adobe Stock in Media Gallery
 
### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Click **Sort by** and verify if the following sort options work
_- Directory: Descending_ 
_- Directory: Ascending_
_- Name: A-Z_
_- Name: Z-A_

### Expected result (*)
The Sorting options work and the images are sorted

### Actual result (*)
The Sorting options do not work

### LINKED ISSUE #1331: Incorrect position of "Licensed" labels in Adobe Stock window
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Have Licensed images for your account

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Click **Search Adobe Stock**
3. **Sign In** Adobe Stock
4. Observe the position of _Licensed_ label

### Expected result (*)
The position of Licensed labels is correct

### Actual result (*)
The position of Licensed labels is incorrect
licensed_label_position

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1330: Sorting by Name and by Directory doesn't work in Media Gallery 
2. magento/adobe-stock-integration#1331: Incorrect position of "Licensed" labels in Adobe Stock window 
### Manual testing scenarios (*)
1. Go to **Content - Media Gallery**
2. Click **Sort by** and verify if the following sort options work
_- Directory: Descending_ 
_- Directory: Ascending_
_- Name: A-Z_
_- Name: Z-A_

### Expected result (*)
The Sorting options work and the images are sorted

1. Go to **Content - Media Gallery**
2. Click **Search Adobe Stock**
3. **Sign In** Adobe Stock
4. Observe the position of _Licensed_ label

### Expected result (*)
The position of Licensed labels is correct

### CODE REVIEW

**Comment by coderimus** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Integration Tests

**Comment by coderimus** [comment]
@Nazar65 thank you for the provided fixes. I tested all of them locally (except the license position, because I am not able to license :) ) and it looks great! Failed tests do not belong to the PR changes. Approve and move to the acceptance tests. 👍 

Name: A-Z
image

Name: Z-A
image

Directory: Descending
image

 Directory: Ascending
image

**Review by coderimus — APPROVED** [review]

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

**Comment by sivaschenko** [comment]
Failed functional tests are not related to the changes

**Pull request merged**
