### PR TITLE
added similar filter code. #557

### PR DESCRIPTION
**Pull request by krirob**
### Description (*)
Added Code for similar filtering

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#557: Add more Adobe Stock search filters support to Client implementation

### Manual testing scenarios (*)

1. Add default filter
                <item name="similar_filter" xsi:type="array">
                    <item name="type" xsi:type="string">similar</item>
                    <item name="condition" xsi:type="string">eq</item>
                    <item name="field" xsi:type="string">297056262</item>
                </item>

### CODE REVIEW

**Comment by diazwatson** [comment]
Hi @krirob many thanks for your contribution.

To help us process your PR could you please fix the warnings in the static test:

```
There was 1 failure:
1) Magento\Test\Php\LiveCodeTest::testCodeStyle
PHP Code Sniffer detected 2 violation(s): 
FILE: ...dobe-stock-client/Test/Unit/Model/SearchParametersProvider/SimilarTest.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 83 | WARNING | [x] Expected 1 newline at end of file; 0 found
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
```

Also, please don't forget to sign the Adobe CLA

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @krirob , it was nice to meet you at the ML EU contribution day and thank you for completing the pull request!

I have an suggestion on how to optimize the implementation of `Similar` filter. What do you think about adding it to `Magento\AdobeStockClient\Model\SearchParametersProvider\SimpleFilters` DI configuration?

**Comment by krirob** [comment]
I don´t think it is wise to use it as a simplefilter. At the moment we don´t know how the UI will use this filter and as with Media ID it needs to be cast to int if it is submited as a string.
And simpelfilter don´t cast to int i think or am i wrong?

**Comment by sivaschenko** [comment]
@krirob agree, casting to int is something SimpleFilters class does not handle

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
