### PR TITLE
#1010: Image size is not passed to image-uploader when inserting an image from new media gallery

### PR DESCRIPTION
**Pull request by konarshankar07**
### Depends on Pull Requests
https://github.com/magento/magento2/pull/27388

### Description (*)

This PR will introduce the new column size in `media_gallery_asset_grid` table which will be used to save the size of the image when media gallery reindexing is perform.
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1010: Image size is not passed to image-uploader when inserting an image from new media gallery

### Manual testing scenarios (*)

**Please ensure Enhanced Media Gallery is Enabled**
1. Login to Admin panel
2. Go to Catalog -> Category
3. Select any category
4. Expand Content fieldset
5. Click "Select from Gallery" button next to "Category Image" field
6. Select any image in the media gallery and click "Add Selected" button

### Expected Result 
image

### Note
**Please merge [magento repo PR](https://github.com/magento/magento2/pull/27388) before merging this one**

### CODE REVIEW

**Comment by sivaschenko** [comment]
Depends on https://github.com/magento/magento2/pull/27388

**Comment by slavvka** [comment]
@run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
magento/magento2#27388 is merged but the static test is failing. please fix it.

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
