### PR TITLE
Refactor image location on Save Preview && License image

### LINKED ISSUE #1771: Image cannot be located if filter is applied
### Preconditions (*)

1. Install Magento 2.4-develop with Adobe Stock Integration and IMS
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery Enabled

### Steps to reproduce (*)

1. Go to Content -> Media Gallery
2. Apply "Show duplicates" filter (or any except "Directory" filters) 
3. Save image preview (or licensed image)
4. Select other directory by clicking on it

### Expected result (*)

No popup

### Actual result (*)

 "The image cannot be located" popup is shown
Peek 2020-08-19 17-31

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1771: Image cannot be located if filter is applied
2. ...

### Manual testing scenarios (*)
1. License image from adobe stock
2. Save preview from adobe stock
3. License image from media gallery

in case 1.2 image must be located anyway
in case 3. image should be only selected

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — DISMISSED** [review]

**Comment by sivaschenko** [comment]
@engcom-Lima please check the "Save Preview", "License", "Save Licensed" and "Open in Media Gallery" for both old and new media gallery

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed 
The following cases have been successfully verified for New Media Gallery. For Old Media Gallery it also works
1. License image from adobe stock
2. Save preview from adobe stock
3. License image from media gallery
Peek 2020-08-20 11-51

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Pull request merged**
