### PR TITLE
[BULK] Aggregated PRs

### PR DESCRIPTION
**Pull request by sivaschenko**
### Included pull requests (*)
* https://github.com/magento/adobe-stock-integration/pull/1282
* https://github.com/magento/adobe-stock-integration/pull/1135
* https://github.com/magento/adobe-stock-integration/pull/1279
* https://github.com/magento/adobe-stock-integration/pull/1280
* https://github.com/magento/adobe-stock-integration/pull/1285
* https://github.com/magento/adobe-stock-integration/pull/1284
* https://github.com/magento/adobe-stock-integration/pull/1259
* https://github.com/magento/adobe-stock-integration/pull/1295

### CODE REVIEW

**Comment by sivaschenko** [comment]
https://m2build-comm.devops.magento.com/job/MTS-API-Tests/9909/

**Comment by sivaschenko** [comment]
@magento run Unit Tests

**Comment by sivaschenko** [comment]
@magento run Functional Tests EE

**Comment by sivaschenko** [comment]
@magento run Functional Tests B2B

**Comment by lenaorobei** [comment]
@magento run Functional Tests EE

**Comment by lenaorobei** [comment]
@magento run Functional Tests B2B

**Comment by lenaorobei** [comment]
@magento run Functional Tests EE

**Comment by lenaorobei** [comment]
@magento run Functional Tests B2B

**Comment by lenaorobei** [comment]
@magento run Functional Tests B2B

**Comment by lenaorobei** [comment]
All user requested https://m2build-ur.devops.magento.com/view/all/job/All-User-Requested-Tests/32068/

**Comment by lenaorobei** [comment]
https://m2build-ur.devops.magento.com/view/all/job/All-User-Requested-Tests/32076/

**Pull request merged**
