### PR TITLE
#1445 :- Create MediaGalleryMetadata and MediaGalleryMetadataApi modules

### LINKED ISSUE #1445: Create MediaGalleryMetadata and MediaGalleryMetadataApi modules
**Story** https://github.com/magento/adobe-stock-integration/issues/1183: Magento extracts image meta data from file

#### Implementation details
Basic module skeleton should be created with minimal required files.
See: https://github.com/magento/adobe-stock-integration/wiki/Technical-Design:-Images-metadata-processing

### AC
- Modules are created

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will introduce the module skeleton for `Magento\MediaGalleryMetadata` and `Magento\MediaGalleryMetadataApi` extension
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1445: Create MediaGalleryMetadata and MediaGalleryMetadataApi modules

### CODE REVIEW

**Comment by konarshankar07** [comment]
@magneto run all tests

**Comment by konarshankar07** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
Thanks for the PR @konarshankar07 ! I will handle the static tests failure

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed
The new modules appeared in Modules List ```php bin/magento module:status``` after enabling them 
modules

**Pull request merged**
