### PR TITLE
IPTC Reader && Writer Implementation for jpeg format

### LINKED ISSUE #1451: Create IPTC reader
**Story** https://github.com/magento/adobe-stock-integration/issues/1183: Magento extracts image meta data from file

#### Description

The `Magento\MediaGalleryMetadata` module should be created in adobe-stock-integration repository.
The `Magento\MediaGalleryMetadataApi` module should be created in adobe-stock-integration repository.
The `Magento\MediaGalleryMetadataApi\Model\ReadMetadataInterface` should be introduced declaring the only method `execute(string $content): array`
The `Magento\MediaGalleryMetadata\Model\Read\Iptc` class should be introduced implementing the `Magento\MediaGalleryMetadataApi\Model\ReadMetadataInterface`
The implementation of `execute` method should extract iptc metadata from the passed image file content.

Reading iptc metadata example:

    $iptcHeaders = [
        'title' => '2#005',
        'headline' => '2#105',
        'keywords' => '2#025'
    ];
    
    getimagesize('image.jpg', $info);
    $decodedMetadata = iptcparse($info['APP13']);
    $keywords = $decodedMetadata[$iptcHeaders['keywords']];
    $title = $decodedMetadata[$iptcHeaders['headline']];

#### Implementation details
See: https://github.com/magento/adobe-stock-integration/wiki/Technical-Design:-Images-metadata-processing

### AC
- Covered with integration tests

### LINKED ISSUE #1454: Create IPTC writer
**Story** https://github.com/magento/adobe-stock-integration/issues/1183: Magento extracts image meta data from file

#### Implementation details
See: https://github.com/magento/adobe-stock-integration/wiki/Technical-Design:-Images-metadata-processing

### AC
- Covered with integration tests

### PR DESCRIPTION
**Pull request by Nazar65**
### Description (*)
**Story** https://github.com/magento/adobe-stock-integration/issues/1183: Magento extracts image meta data from file
Introduced IPTC reader and writer for all supported image formats

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1451: Create IPTC reader
2. Fixes magento/adobe-stock-integration#1454: Create IPTC writer

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — DISMISSED** [review]

**Comment by sivaschenko** [comment]
https://github.com/magento/adobe-stock-integration/issues/1554 removed from description as it still should be handled for PNG

**Comment by sivaschenko** [comment]
Integration tests have been extracted to a separate pull request to merge the prototype and address the infrastructure issue with integration tests separately

**Comment by sivaschenko** [comment]
Integration tests in https://github.com/magento/adobe-stock-integration/pull/1560

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Pull request merged**
