### PR TITLE
[WIP] Utilizing Files API implementation of SDK

### PR DESCRIPTION
**Pull request by sivaschenko**
Utilizing Files API implementation of SDK introduced by @gabrieldagama in https://github.com/adobe/stock-api-libphp/pull/13

### CODE REVIEW

**Comment by sivaschenko** [comment]
Help with stabilizing the tests on this PR is highly appreciated!

**Comment by coderimus** [comment]
@sivaschenko I will adjust tests ASAP.

**Comment by sivaschenko** [comment]
@coderimus thank you vm!

**Comment by coderimus** [comment]
@sivaschenko PR provided: https://github.com/magento/adobe-stock-integration/pull/1224 
Did it in a separate branch caused find problems to push to yours :(

**Comment by sivaschenko** [comment]
Closing in favour to https://github.com/magento/adobe-stock-integration/pull/1224

**Pull request closed without merging**
