### PR TITLE
Fix Escape doesn't close the "Couldn't log you in..." message. Instead the Adobe Stock window is closed

### LINKED ISSUE #1542: Escape doesn't close the "Couldn't log you in..." message. Instead the Adobe Stock window is closed
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Provided _API Key (Client ID)_ 
4. Not provided _Client Secret_
client_key

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**, click **Search Adobe Stock**
2. Click **Sign In**
_Couldn't log you in. Login failed. Please check if the Secret Key is set correctly and try again._ message appears
3. Hit Escape button from keyboard

### Expected result (*)
The _Couldn't log you in..._ message is closed

### Actual result (*)
Adobe Stock is closed, but the message is not
Peek 2020-06-26 12-43

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1542: Escape doesn't close the "Couldn't log you in..." message. Instead the Adobe Stock window is closed

### Manual testing scenarios (*)
1. Go to **Content - Media Gallery**, click **Search Adobe Stock**
2. Click **Sign In**
_Couldn't log you in. Login failed. Please check if the Secret Key is set correctly and try again._ message appears
3. Hit Escape button from keyboard

The _Couldn't log you in..._ message is closed

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run Static Tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

The _"Couldn't log you in..."_ message is closed on Escape button

**Pull request merged**
