### PR TITLE
 Fix "Search by keyword" doesn't find images in Media Gallery

### LINKED ISSUE #1301: `Search by keyword` filter dismiss other filters
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

1. Upload image with name `a4`
2. Search this image by search input
image
3. Apply filter `Source` - `Adobe Stock`
image

### Expected result (*)

Image can't be found because it was uploaded

### Actual result (*)

Image is found

### LINKED ISSUE #1317: "Search by keyword" doesn't find images in Media Gallery
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. An image saved from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image saved from Adobe Stock
3. Click on _three dots_ and select **View Details**
4. Select one of the **Tags** and copy it. Close Image Details
5. Paste the copied text into _Search by keyword_ field and click Search :mag: 

### Expected result (*)
The image is found 

### Actual result (*)
The image is not found
search_by_keywords

### Note
- All the keywords are exist in ```media_gallery_keyword``` table

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)
Fixes #1301: "Search by keyword" filter dismiss other filters
Fixes #1317: "Search by keyword" doesn't find images in Media 

### Manual testing scenarios (*)
1. Go to **Content - Media Gallery**
2. Select an image saved from Adobe Stock
3. Click on _three dots_ and select **View Details**
4. Select one of the **Tags** and copy it. Close Image Details
5. Paste the copied text into _Search by keyword_ field and click Search :mag: 

### Expected result
The image is found, other applied filters are not dismissed

### CODE REVIEW

**Review by sivaschenko — APPROVED** [review]

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

**Comment by sivaschenko** [comment]
Relaunching the MFTF tests as not only PayPal but also EndToEndB2CLoggedInUserTest has failed

**Comment by sivaschenko** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sivaschenko** [comment]
The Functional Tests B2B are failing due to PayPal rate limit: https://jira.corp.magento.com/browse/MC-33951

**Pull request merged**
