### PR TITLE
Move component names to xml configutation, fix save preview on standalone page && adobe stock info on gallery page

### LINKED ISSUE #979: Impossible to 'Save Preview' or 'License and Save'. An "UncaughtType Error" appears
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enable Enhanced Media Gallery in Stores -> Configuration -> Advanced -> System 
enhansedMG

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Click **Search Adobe Stock** and click on any image, so the Preview is displayed
4. Click **Save Preview**, and **Confirm** File Name
5. Open dev console in the web browser

### Expected result (*)
The image preview is saved to Media Gallery, no errors appear in browsers dev console 

### Actual result (*)
An :negative_squared_cross_mark: _UncaughtType Error_ appears, the image **preview is not saved** to Media Gallery
```
actions.js:156 Uncaught TypeError: Cannot read property 'activeNode' of undefined
    at UiClass.save (actions.js:156)
    at UiClass.<anonymous> (actions.js:122)
    at $.<computed>.<computed>.closeModal (prompt.js:164)
    at $.<computed>.<computed>.closeModal (jquery-ui-1.9.2.js:432)
    at HTMLButtonElement.dispatch (jquery.js:5232)
    at HTMLButtonElement.elemData.handle (jquery.js:4884)
save @ actions.js:156
(anonymous) @ actions.js:122
closeModal @ prompt.js:164
(anonymous) @ jquery-ui-1.9.2.js:432
dispatch @ jquery.js:5232
elemData.handle @ jquery.js:4884
```
uncought_type_error

### Additional info,

The same result if attempt to **License and Save** an image
license

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)
Fixed save action on standalone media gallery page.

### Manual testing scenarios (*)

    From Admin go to Content - Media Media Gallery
    Select an image added from Adobe Stock
    Click on three dots, select View Details
    Verify Adobe Stock details

 From Admin go to Content - Media Media Gallery
Click on Adobe Stock Search Button
 try to save image, or license image

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Review by VladimirZaets — DISMISSED** [review]

**Comment by sivaschenko** [comment]
@magento run Functional Tests B2B

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
