### PR TITLE
Cover with unit tests DocumentToAsset class an UserProfileRepository

### PR DESCRIPTION
**Pull request by engcom-Golf**
### Description (*)
Cover with unit tests DocumentToAsset class an UserProfileRepository

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#364: Cover UserProfileRepository with unit tests

### CODE REVIEW

**Comment by diazwatson** [comment]
Thanks for this contribution @engcom-Golf 

What do you think about increasing the coverage for the whole module?
Screenshot 2019-08-19 at 02 04 03

**Comment by engcom-Golf** [comment]
Hi @diazwatson yes, sure why not :)

**Comment by engcom-Golf** [comment]
@diazwatson Done :heavy_check_mark:

**Review by diazwatson — APPROVED** [review]
Nice!!! Great job!

**Pull request merged**
