### PR TITLE
Several fixes for Internet explorer & edge

### LINKED ISSUE #1081: Image Preview is broken on Internet Explorer & Edge
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop
Internet Explorer 11 or Microsoft Edge 44...

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enable Enhanced Media Gallery in Stores -> Configuration -> Advanced -> System 
enhansedMG
4. An image added to Media Gallery

### Steps to reproduce (*)
1. Open Magento instance on _Microsoft Internet Explorer_ OR _Edge_ web browser
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Click **Search Adobe Stock** button
4. Open Preview of any image

### Expected result (*)
The preview is properly displayed

### Actual result (*)
The Preview is broken. No Image attributes, More From Series, Model ...
IE_preview_grid

### LINKED ISSUE #1303: Extra white space on Media Gallery grid (Not Standalone Media Gallery)
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Images added to Media Gallery
4. Enhanced Media Gallery Enabled

### Steps to reproduce (*)
1. Go to **Catalog - Products** and click **Add Product**
2. Expand **Content**, click **Show / Hide Editor** **Insert Image**
3. Observe the right side of Media Gallery Grid

### Expected result (*)
No white space, like on Standalone Media Gallery
empty space_expected

### Actual result (*)
Extra white space
empty space_actual

### LINKED ISSUE #1308: Empty spots in "Sort by" drop-down list (Internet Explorer & Edge)
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Magento Instance opened in Internet Explorer

### Steps to reproduce
1. Open Magento Instance on Internet Explorer or Edge web browser 
2. Go to **Content - Media Gallery**
3. Click on **Sort by** drop-down 

### Actual result
Empty spots in the drop-down list
sort_IE_EDGE

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1081: Image Preview is broken on Internet Explorer & Edge
2. magento/adobe-stock-integration#1308: Empty spots in "Sort by" drop-down list (Internet Explorer & Edge)
3. magento/adobe-stock-integration#1303: 
Extra white space on Media Gallery grid (Not Standalone Media Gallery)

### Manual testing scenarios (*)
1. Go to **Catalog - Products** and click **Add Product**
2. Expand **Content**, click **Show / Hide Editor** **Insert Image**
3. Observe the right side of Media Gallery Grid

No white space, like on Standalone Media Gallery
No Empty spots in the drop-down list sortBy
The preview is properly displayed

### CODE REVIEW

**Comment by coderimus** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by coderimus** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by coderimus — APPROVED** [review]
@Nazar65 thank you for the provided fixes. 👍 Let's wait for tests finishing and move to the acceptance tests.

**Comment by coderimus** [comment]
Test failed due to the Adobe Stock errors this day. I move PR to the acceptance testing to move forward. Tests should be run later.

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

**Comment by sivaschenko** [comment]
The Functional Tests B2B are failing due to PayPal rate limit: https://jira.corp.magento.com/browse/MC-33951

**Pull request merged**
