### PR TITLE
Added MFTF test that tests the see more from same model button

### PR DESCRIPTION
**Pull request by semajeg**
Added MFTF test that tests the see more from same model button when searching

issue #451

### CODE REVIEW

**Comment by diazwatson** [comment]
Hi @semajeg thanks for your contribution.
I am currently trying to run the test but when doing it I get this error:

```
$ bin/mftf run:test AdminAdobeStockImagePreviewSameModelSeeMoreTest

In TestGenerator.php line 161:

  Cannot reference test configuration for generation without accompanying suite.
$
```
Have you seen this before?
Do I need to configure something in particular in order to run this test?

**Comment by sivaschenko** [comment]
Hi @diazwatson the test has correct group assigned `adobe_stock_integration` so it should have the accompanying suite: `AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration.xml`

Could you try to rebuild the project or use `--remove` option for running the test

**Comment by semajeg** [comment]
Sorry, realised I posted that previous comment from my work account, so I deleted it and I'm re-adding now:

Hey @diazwatson, I'll take a look tonight and see if I can reproduce that if the suggestion from @sivaschenko doesn't solve it.

Also @sivaschenko there are a number of tests that are failing which are not to do with stuff I've changed, is this expected?

**Comment by sivaschenko** [comment]
@semajeg we are stabilizing Static and Integration tests currently. Sample Data Tests and coverage fails do not look to be valid - random failure

**Review by filmaj — APPROVED** [review]
LGTM! Ran and passed locally.

**Pull request merged**
