### PR TITLE
[WIP]: Adjust get image details to the latest MediaGallery update.

### PR DESCRIPTION
**Pull request by coderimus**
### Description (*)
This PR will provide changes to the View Details functionality after the https://github.com/magento/magento2/pull/27499 will be merged.

Depends on: https://github.com/magento/adobe-stock-integration/pull/1235

### CODE REVIEW

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @coderimus thanks for the pull request! Can you please update the branch and resolve conflicts.

Also, please take a look on recently merged changes in https://github.com/magento/adobe-stock-integration/pull/1175

**Comment by coderimus** [comment]
@sivaschenko thank you for the mentioned  PR: https://github.com/magento/magento2/pull/27499
I also merged 1.1-develop to the PR's branch and see that changes provided by me do not have practical value. However, I do not want to close this PR because when the https://github.com/magento/magento2/pull/27499 will be merged I can adjust view details to the newly provided changes.

**Comment by sivaschenko** [comment]
@coderimus https://github.com/magento/magento2/pull/27499 is merged, however, there is another dependency: https://github.com/magento/adobe-stock-integration/pull/1235

**Comment by coderimus** [comment]
I close this PR because of asset details already implemented.

**Pull request closed without merging**
