### PR TITLE
Fix Adobe Stock Integration SOAP WebAPI tests

### LINKED ISSUE #1839: Fix Adobe Stock Integration WebAPI tests
Adobe Stock Integration WebAPI tests are not currently running on builds on the pull request.

The tests have to be launched locally and fixed.

Current failures:

```
Magento\AdobeStockAsset\Test\Api\AssetRepository\DeleteByIdTest::testDelete
Parameters in fault details are invalid.
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    1 => 1
+    'id' => '1'
 )

```

```
Magento\AdobeStockAsset\Test\Api\AssetRepository\GetByIdTest::testGetAssetById
SoapFault: looks like we got no XML document
```

```
Magento\AdobeStockAsset\Test\Api\AssetRepository\GetListTest::testGetList
TypeError: Argument 1 passed to Magento\Framework\Api\SimpleDataObjectConverter::convertKeysToCamelCase() must be of the type array, object given, called in /var/www/html/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Soap.php on line 54
```

```
Magento\AdobeStockImage\Test\Api\SearchExecuteTest::testSearchExecute
SoapFault: Adobe API Key is invalid!
```

To run the tests on PR - a related infrastructure should be added, see example: https://github.com/magento/partners-magento2-infrastructure/pull/39/files

Build with failures: http://10.234.235.163:8080/job/WebAPI-Tests/2552
Jira: https://jira.corp.magento.com/browse/ENGCOM-8228

### PR DESCRIPTION
**Pull request by engcom-Golf**
### Description (*)

Fixes Adobe Stock Asset module SOAP Web API tests fail

### Related Pull Requests
https://github.com/magento/partners-magento2-infrastructure/pull/40

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1839: Fix Adobe Stock Integration WebAPI tests

### Manual testing scenarios (*)

No manual testing required

### CODE REVIEW

**Comment by engcom-Golf** [comment]
@magento run WebAPI Tests

**Comment by sivaschenko** [comment]
@magento run Semantic Version Checker,Magento Health Index

**Comment by engcom-Golf** [comment]
@magento run WebAPI Tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Pull request merged**
