### PR TITLE
#1599: Underscore symbol is not allowed in Image name and Description. (Edit window)

### LINKED ISSUE #1599: Underscore symbol is not allowed in Image name and Description. (Edit window)
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. **Upload** an image with name containing underscore symbol, _test_1_ for example
3. Click on "three dots" near the image and select **Edit**
4. Do not, change anything, click **Save**
Peek 2020-07-15 17-05

### Expected result (*)
The image is saved. 

### Actual result (*)
The image name doesn't pass the validation
underscore_validation
The image name, containing underscore, can be saved from Adobe Stock and Uploaded locally. Allow also to Edit.

### LINKED ISSUE #1603: Add comma and dot to allowed symbols in Description field. (Edit window)
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select a file and click on "three dots", select Edit
3. Into the **Description field** type sentence containing dot (.) and a comma(,)
4. Click **Save** 

### Expected result (*)
The image is saved. 

### Actual result (*)
The text dosn't pass the validation. 
description

### PR DESCRIPTION
**Pull request by joweecaquicla**
### Description (*)

This PR will introduce fixes to the validation bugs found in Image Edit Details panel.
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration https://github.com/magento/adobe-stock-integration/issues/1599: Underscore symbol is not allowed in Image name and Description. (Edit window) 
2. Fixes magento/adobe-stock-integration https://github.com/magento/adobe-stock-integration/issues/1603: Add comma and dot to allowed symbols in Description field. (Edit window)

### Manual testing scenarios (*)

**For 1599:**
1. Go to **Content - Media Gallery**
2. Upload an image with name containing underscore symbol, test_1 for example
3. Click on "three dots" near the image and select Edit
4. Do not, change anything, click Save
5. The image should still be saved.

**For 1603:**
1. Go to Content - Media Gallery
2. Select a file and click on "three dots", select Edit
3. Into the Description field type sentence containing dot (.) and a comma(,)
4. Click Save
5. The image should be saved.

### CODE REVIEW

**Comment by joweecaquicla** [comment]
@magento run all tests

**Review by sivaschenko — DISMISSED** [review]

**Review by chalov-anton — CHANGES_REQUESTED** [review]
:x: QA Failed

The symbols:dots (.), commas(,), underscores (_), dashes (-) are added to Allowed
But it is impossible to save Image Details with empty _Description_
empty_desc

**Comment by joweecaquicla** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

symbols

Empty Description can also be saved successfully

**Pull request merged**
