### PR TITLE
`Search by keyword` filter dismiss other filters

### LINKED ISSUE #1301: `Search by keyword` filter dismiss other filters
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

1. Upload image with name `a4`
2. Search this image by search input
image
3. Apply filter `Source` - `Adobe Stock`
image

### Expected result (*)

Image can't be found because it was uploaded

### Actual result (*)

Image is found

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Closes #1301

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1301:`Search by keyword` filter dismiss other filters
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### CODE REVIEW

**Review by coderimus — CHANGES_REQUESTED** [review]
Hello @engcom-Charlie ! Thank you for the provided fix. Please, check the static tests from the ci build. Looks like there is one minor issue with the get method.

**Review by coderimus — APPROVED** [review]
@engcom-Charlie looks good as for me 👍 Move to the acceptance test.

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

**Comment by sivaschenko** [comment]
Merged to https://github.com/magento/adobe-stock-integration/pull/1319

**Pull request closed without merging**
