### PR TITLE
[MFTF] Cover test scenario #1009

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Covered test scenario https://github.com/magento/adobe-stock-integration/issues/1009
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1009: [MFTF] Cover "License Adobe Stock Images?" message should not popup when user is not logged in and tries to License and Save an already Licensed image

### Manual testing scenarios (*)

Please see https://github.com/magento/adobe-stock-integration/issues/1009

### CODE REVIEW

**Comment by sivaschenko** [comment]
@engcom-Charlie looks like the test have failed https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/adobe-stock-integration/pull/1030/fb5f50cea96fd5ab6f6bc99f2c224a97/Functional/allure-report-ce/index.html#suites/72cc2642d075063419e3af6e7af8f26a/2dc4faca20c9327c/

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
This PR covers the test scenario #1009 and fixed `AdminAdobeStockSignInSignOutTest`.

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
