### PR TITLE
Remove Source filter

### LINKED ISSUE #1731: Move Source filter to the MediaGalleryUi module
### Preconditions (*)
Source filter in MediaGallery Should be moved to the MediaGalleryUi module

### Steps to reproduce (*)
1. `Magento\AdobeStockImageAdminUi\Ui\Component\Listing\Columns\Source\Options` should be moved to the MediaGalleryUi module with only Local option
2. Source filter from UI component should be removed from AdobStockIMageAdminUi module and declarated in MediaGalleryUi module
3. Plugin should be added in AdobStockImageAdminUi module to add AdobeStock Source option to the Source filter

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1731:Move Source filter to the MediaGalleryUi module
2. ...

### Manual testing scenarios (*)

1.     Open new enhanced media gallery
2.     Expand Filters tab
3.     Apply Source filter

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
Please test together with https://github.com/magento/magento2/pull/29405

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

Check the comment on dependent Magento2 PR https://github.com/magento/magento2/pull/29405#issuecomment-669257015

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

See the comment on dependent Magento2 PR https://github.com/magento/magento2/pull/29405#issuecomment-669257015

**Comment by lenaorobei** [comment]
@magento run all tests

**Pull request merged**
