### PR TITLE
Improve media gallery styles && directory filters state

### LINKED ISSUE #1187: The image from Media Gallery is not found via "Search by keyword" if a part of name is searched for
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop
Internet Explorer 11 or Microsoft Edge 44...

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. **An image Uploaded to Media Gallery with name, for example, _Selection_007.png_**

### Steps to reproduce (*)
1. From Admin Go to **Content** - **Media Gallery**
2. Into the _Search by keyword_ field type, for example, **_Select_** or **__Selection__** 
3. Click **Search** 

### Expected result (*)
The image _Selection_007.png_ is found

### Actual result (*)
The image _Selection_007.png_ is not found until the **full** image name _selection_007_ is searched for
search_in_media_gallery_2020-04-10

### Note
For example, in Catalog - Products, if there is a _Product_007_ and you search for _prod_, it is found

### LINKED ISSUE #1217: Move folder name lower in the folder tree
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Have folder and subfolder in Media Gallery folder tree 

### Steps to reproduce (*)
1. From Admin Go to **Content** - **Media Gallery**
2. Observe the folder name position in folder tree

### Expected result (*)
The folder name is closer to the center of the row

### Actual result (*)
fold_name_center

### LINKED ISSUE #1220: Add distance between image name, ST symbol, extension. [All web browsers]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Images with long names added to Media Gallery, use _hyphen -_ symbol in names  
4. **Instance opened in Internet Explorer browser**

### Steps to reproduce (*)
1. From Admin go to **Content** - **Media - Media Gallery** 
2. Observe the images names and extensions

### Expected result (*)
Distance between image name, ST symbol, extension

### Actual result (*)
extension_st

### LINKED ISSUE #1221: Directory filter consider image names
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. 

### Steps to reproduce (*)
1. From Admin Go to **Content** - **Media Gallery**
2. **Create Folder** root with name _1_, for example
3. Select the previously created folder _1_, and **Upload** for example, an image named **_image 2_**
4. **Create Folder** root with name _2_, for example
5. Select folder _2_ and observe if it contains images

### Expected result (*)
The newly created folder is empty

### Actual result (*)
The newly created folder contains image from folder _1_. ```media-gallery:index``` does not remove the folder _2_ content
name_2_foled_image

### Note
- the investigation discovered that that _/pub/media/2_ folder is empty. This issue happens because the _Active filters: Directory: **2**_ is applied, and the image name contains _2_ in it

### LINKED ISSUE #1222: "Active filters: Directory" remains applied when the last folder in Media Gallery has been deleted
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. **Have ONLY two root folders, containing images, in Media Gallery. Name the folders "1" and "2" for example**

### Steps to reproduce (*)
1. From Admin Go to **Content** - **Media Gallery**
2. Select folder _2_. Verify that _Active filters: Directory: 2_ is applied 
3. **Delete Folder** _2_
4. Verify that _Active filters: Directory: 1_ is applied
5. **Delete Folder** _1_

### Expected result (*)
_Active filters: Directory:_ is NOT applied

### Actual result (*)
_Active filters: Directory: 1_ remains applied. All the images from folder _1_ are displayed. Trying to delete an image leads to errors 
400_bad request_active filters

### LINKED ISSUE #1232: Image description doesn't match the UI Prototype
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Have images added to Media Gallery

### Steps to reproduce (*)
1. From Admin go to **Content** - **Media - Media Gallery** 
2. Observe the image description (under the image)

### Expected result (*)
The image description matches [UI Prototype](https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/5fdf6279-e5c1-4e10-903f-1fbc4a4486b3/Image-selected)

### Actual result (*)
The image description doesn't match the UI Prototype 
image_description

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)
1. magento/adobe-stock-integration#1217: Move folder name lower in the folder tree
2. magento/adobe-stock-integration#1220: Add distance between image name, ST symbol, extension. [All web browsers]
3. magento/adobe-stock-integration#1222 "Active filters: Directory" remains applied when the last folder in Media Gallery has been deleted
4. magento/adobe-stock-integration#1221 Directory filter consider image names 
5. magento/adobe-stock-integration#1232 Image description doesn't match the UI Prototype 
6. magento/adobe-stock-integration#1205: Search by keywords does not work
7. magento/adobe-stock-integration#1187: The image from Media Gallery is not found via "Search by keyword" if a part of name is searched for

### Manual testing scenarios (*)
1. From Admin go to **Content** - **Media - Media Gallery** 
2. Observe the images names and extensions'

The folder name is closer to the center of the row
Distance between image name, ST symbol, extension

### CODE REVIEW

**Review by sivaschenko — DISMISSED** [review]

**Comment by chalov-anton** [comment]
:x:  #1221 Directory filter consider image names

**Review by chalov-anton — CHANGES_REQUESTED** [review]
:x: #1221 Directory filter consider image names
Still reproducible for subfolders.
If there is a folder named _**a**_ with subfolder named _**b**_ in it. The folder _**a**_ contains an image named _**b**_. In this case, the folder _**b**_ will display image _**b**_ in it, because there names match
folder_subfolder_structure 2020-04-22 11-38

:x: #1187: The image from Media Gallery is not found via "Search by keyword" if a part of name is searched for 
Still reproducible with the steps described in the issue 
OR take a look at another case:
There is an image named _**Neon effect picture of man wearing medical**_ 
If try to Search for: **_Neo_** or **_effec_** or **_pictur_** or **_wearin_** ... the image will not be found 
search_2020-04-22 11-50

**Comment by Nazar65** [comment]
@chalov-anton could you please recheck ? thanks

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

**Comment by lenaorobei** [comment]
@magento run Functional Tests B2B

**Pull request merged**
