### PR TITLE
Licensing frontend implementation refactoring

### PR DESCRIPTION
**Pull request by sivaschenko**
### Description (*)
Image licensing frontend functionality will be adjusted in this pull requests

### Fixed Issues (if relevant)
1. magento/adobe-stock-integration#1228: Image preview is broken (Licensing) 
2. magento/adobe-stock-integration#1241: No message is displayed if try to License an image from Standalone Media Gallery with NO secret key 

### Testing scenarios

The following functionality/areas can be potentially affected:
Adobe Stock Integration preview actions:
 * Save preview
 * Save licensed image
 * License and save image
 * Login during licensing
 * Licensing cases when the preview image was already saved or not

Adobe Stock Integration confirmation popups:
 * Save preview
 * Save licensed, preview was not saved before
 * License and save (preview was not saved before)
 * License and save (preview was saved before)
 * Not enough credits to license an image

Adobe Stock Integration overlay:
 * Licensed overlay

Enhanced Media Gallery:
 * License an image from media gallery

### Includes pull requests (*)
https://github.com/magento/adobe-stock-integration/pull/1263
https://github.com/magento/adobe-stock-integration/pull/1249

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Please address builds failures

**Comment by sivaschenko** [comment]
https://m2build-comm.devops.magento.com/job/MTS-API-Tests/9805

**Comment by sivaschenko** [comment]
https://m2build-comm-2.devops.magento.com/job/MTS-API-Tests/9903/

**Review by Nazar65 — DISMISSED** [review]

**Review by engcom-Charlie — DISMISSED** [review]

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

**Comment by lenaorobei** [comment]
@magento run Functional Tests EE

**Pull request merged**
