### PR TITLE
[WIP] #828 : Update media gallery grid styles to match the mockups

### PR DESCRIPTION
**Pull request by konarshankar07**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#828: Update media gallery grid styles to match the mockups

### Manual testing scenarios (*)

1. Login to Admin Panel
2. Select "Media Gallery Development" from the menu on the right

### Expected Result
image

### CODE REVIEW

**Comment by Nazar65** [comment]
Hi @konarshankar07 but they actually pass the mockups isn't it ?

**Comment by konarshankar07** [comment]
Hello @Nazar65 ...
I have done the styling as per the screenshot attached to the ticket. But I think the attached screenshot might be outdated. 
image

**Comment by sivaschenko** [comment]
@konarshankar07 thank you for the pull request!

Looks like the styling is not responsible, can you try to resize the browser window.

Actually the current styling on 1.1-develop branch is generally ok, however, we may want to make the images just a little bit bigger and ensure the vertical and horisontal pictures are represented correctly without deformations and cropping.

Also, I think there is no need to preserve the space for the directory tree - once it will be added it will push the images to the right anyway

**Comment by konarshankar07** [comment]
@sivaschenko ... Please check the following screenshot and let me know your feedback
image

Thanks

**Comment by sivaschenko** [comment]
@konarshankar07 Thanks for the screen shot! I think it would be good to reduce the grey space around the images in general. Also, if image is vertical - the grey space should be minimal on top and bottom, if the image is gorizontal - the grey space should be minimal on left and right side.

Can you please include the vertical and horizontal images on the screenshot for better visibility.

Also, please update the branch and use at least one downloaded preview image from Adobe Stock - to ensure that the "Unlicensed" label is not shifted by the style changes.

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
The images which is in the screenshot is very small like 100X100 px but I will upload screenshot with some Adobe stock preview images

**Comment by konarshankar07** [comment]
@sivaschenko 
Here is the screenshot of the Adobe Stock Image preview images
image

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@konarshankar07 looks good, the only thing - I've decreased padding around pictures

**Pull request merged**
