### PR TITLE
[MFTF] fix and unskip AdminMediaGalleryCreateDeleteFolderTest

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1141: AdminMediaGalleryCreateDeleteFolderTest is failing
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
