### PR TITLE
Fix: Error when loading grid after logout on adobe side

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#433: Error when loading grid after logout on adobe side

### Manual testing scenarios (*)

1.     Login to Admin panel
2.     Open Adobe Stock grid (Catalog -> Categories -> Content -> Select from Gallery -> Search Adobe Stock)
3.     Log in to Adobe: Click "Sign in" link in top right corner (or initiate image licensing process clicking "License" button in any image preview)
4.     Go to adobe.com in a new tab and logout
5.     Return to Magento Admin panel tab, refresh it and reopen the grid

 **Grid  loaded for unauthorized user**

### CODE REVIEW

**Comment by diazwatson** [comment]
Hi @Nazar65 , thanks for this contribution.

Could you please review the integration test of this class:

```
There was 1 failure:
1) Magento\AdobeStockClient\Test\Integration\Model\ClientTest::testSearch
Failed asserting that 0 matches expected 3.
/home/travis/build/magento/adobe-stock-integration/ext/magento/adobe-stock-integration/AdobeStockClient/Test/Integration/Model/ClientTest.php:104
```

**Review by diazwatson — CHANGES_REQUESTED** [review]
Hi @Nazar65 , thanks for this contribution.

Could you please review the integration test of this class:

```
There was 1 failure:
1) Magento\AdobeStockClient\Test\Integration\Model\ClientTest::testSearch
Failed asserting that 0 matches expected 3.
/home/travis/build/magento/adobe-stock-integration/ext/magento/adobe-stock-integration/AdobeStockClient/Test/Integration/Model/ClientTest.php:104
```

**Comment by Nazar65** [comment]
hi @diazwatson i'm, currently working on this. thanks for note.

**Comment by Nazar65** [comment]
@diazwatson  done :heavy_check_mark:

**Review by sivaschenko — DISMISSED** [review]

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
