### PR TITLE
Fix static tests failures on 2.0-develop per new rules

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)
1.Verify MediaGallery messages displayed correctly,
2. Verify Adobe Stock Configuration displayed correctly
3. Verify Adobe stock sign in sign out functionality and styles.

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
