### PR TITLE
#14 : Implement content type search filter

### PR DESCRIPTION
**Pull request by konarshankar07**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#14: Implement content type search filter

### CODE REVIEW

**Comment by konarshankar07** [comment]
Hello @sidolov ,
I've added the content type filter but it is not working. Please check and let me know if I've implemented wrong.

Thanks

**Review by sidolov — CHANGES_REQUESTED** [review]
Hi @konarshankar07 , you implemented the only frontend part, you also need to handle this filter on the backend - `\Magento\AdobeStockClient\Model\SearchParametersProvider\ContentType`. Please, check another filter as an example: `\Magento\AdobeStockClient\Model\SearchParametersProvider\Orientation`

**Comment by konarshankar07** [comment]
Thanks @sidolov for the guidance. I've add the backend code for content type filters

**Comment by sidolov** [comment]
Hi @konarshankar07 , I have refactored implementation just a little bit. Now it's done. Thank you!

**Review by sidolov — APPROVED** [review]

**Pull request merged**
