### PR TITLE
Internet explorer improvements && styles improvements

### LINKED ISSUE #1162: Long image names are not cut in Media Gallery on Internet Explorer and Edge web browsers
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop
Internet Explorer 11 or Microsoft Edge 44...

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. **An image added to Media Gallery with a long name, for example, _Transformer-Open-and-Short-Circuit-Tests_1.png_**

### Steps to reproduce (*)
1. Open Magento instance on _Microsoft Internet Explorer_ OR _Edge_ web browser
2. Go to **Content** - **Media Gallery**
3 Verify the previously uploaded images name in the Media Gallery 

### Expected result (*)
A long image name should be displayed with three dots **(...)** at the end

### Actual result (*)
The image name is transferred to another row, and it is cut at the bottom 
IE_names_cut

### LINKED ISSUE #1167: Wrong button order when an image is selected [Internet Explorer]
I'm having the same Magento instance opened on the same machine but in two different Web Browsers

### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enable Enhanced Media Gallery in Stores -> Configuration -> Advanced -> System 
enhansedMG
4. An image added to Media Gallery
5. **Instance opened in Internet Explorer browser**

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Select an image from Media Gallery (left mouse click)
_(**Add Selected** button apeared)_

### Expected result (*)
**Search Adobe Stock** is the last button, **Add Selected** is the last but one 

### Actual result (*)
**Add selected is the last but one button
IE_button_order

### LINKED ISSUE #1219: Image extension is cut in Media Gallery [Internet Explorer]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Images with long names added to Media Gallery, use _hyphen -_ symbol in names  
4. **Instance opened in Internet Explorer browser**

### Steps to reproduce (*)
1. From Admin go to **Content** - **Media - Media Gallery** 
2. Observe the images names and extensions

### Expected result (*)
name_extension_Chrome

### Actual result (*)
The images extension is cut
name_extension_IE

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1219: Image extension is cut in Media Gallery [Internet Explorer]
2. magento/adobe-stock-integration#1162: Long image names are not cut in Media Gallery on Internet Explorer and Edge web browsers
3. magento/adobe-stock-integration#1167: Wrong button order when an image is selected [Internet Explorer]

### Manual testing scenarios (*)
1. Open Magento instance on _Microsoft Internet Explorer_ OR _Edge_ web browser
2. Go to **Content** - **Media Gallery**
3 Verify the previously uploaded images name in the Media Gallery 

**Search Adobe Stock** is the last button, **Add Selected** is the last but one 
Observe the images names and extensions

### CODE REVIEW

**Comment by sivaschenko** [comment]
https://m2build-comm-2.devops.magento.com/job/MTS-API-Tests/10203/

**Review by sivaschenko — APPROVED** [review]

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

**Comment by coderimus** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Sample Data Tests B2B

**Comment by sivaschenko** [comment]
The Functional Tests B2B are failing due to PayPal rate limit: https://jira.corp.magento.com/browse/MC-33951

**Pull request merged**
