### PR TITLE
#967 :- Overlay is not shown if overlay column is specified in listing xml after the image (url) column

### LINKED ISSUE #967: Overlay is not shown if overlay column is specified in listing xml after the image (url) column
### Preconditions (*)
1. Install Magento and Adobe Stock Integration [See documentation](https://github.com/magento/adobe-stock-integration/wiki/Installation-Guide)
2. Have at least one Adobe Stock preview image saved to the media gallery
3. Edit source code and remove the sort order from https://github.com/magento/adobe-stock-integration/blob/89109a9e29299e076e3071177f0c210ed75041b2/AdobeStockImageAdminUi/view/adminhtml/ui_component/media_gallery_listing.xml#L32

### Steps to reproduce (*)
1. Login to Admin panel
2. Open Media Gallery (i.e. Catalog -> Category -> expand Content -> Select from Gallery button)

### Actual result (*)
The "Unlicensed" overlay is not displayed

### Expected result (*)
The overlay should be displayed

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will fix the overlay issue with enhanced media gallery enabled
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#967: Overlay is not shown if overlay column is specified in listing xml after the image (url) column

### Related Pull Requests
https://github.com/magento/magento2/pull/27981

### Manual testing scenarios (*)

1. Login to Admin panel
2. Open Media Gallery (i.e. Catalog -> Category -> expand Content -> Select from Gallery button)

### Expected Result
image

### CODE REVIEW

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @konarshankar07 ! I believe this fix is applicable only for new media gallery. Can you please ensure any custom masonry grid created with overlay component is not dependent on particular columns sequence

**Comment by coderimus** [comment]
Hello @konarshankar07 ! Thank you for the work you have done! The latest main branch updates changed one file related to this PR. Please, update your changes and resolve conflicts.

**Comment by konarshankar07** [comment]
Hello @sivaschenko ...
I just tested the overlay styling with your [sivaschenko/masonry-grid-example](https://github.com/sivaschenko/masonry-grid-example) module and I haven't seen any issue with the overlay styling
image
Thanks

**Review by sivaschenko — DISMISSED** [review]

**Comment by sivaschenko** [comment]
Test steps:
1. move the `<column name="overlay"` in corresponding UI listing XML to be the last column.
2. Flush cache
3. Review the grid UI

This pull request needs to be tested on:
Enhanced Media Gallery Grid
Standalone Enhanced Media Gallery Grid
Adobe Stock Integration Grid
Custom Masonry Grid (https://github.com/sivaschenko/masonry-grid-example)

**Review by chalov-anton — CHANGES_REQUESTED** [review]
> Test steps:
> 
> 1. move the `<column name="overlay"` in corresponding UI listing XML to be the last column.
> 2. Flush cache
> 3. Review the grid UI
> 
> This pull request needs to be tested on:
> Enhanced Media Gallery Grid
> Standalone Enhanced Media Gallery Grid
> Adobe Stock Integration Grid
> Custom Masonry Grid (https://github.com/sivaschenko/masonry-grid-example)

:x: QA Failed

- In Adobe Stock Image Grid, the licensed label is moved a few pixels up  
up_licen

- In Custom Masonry Grid 
up_licen_labels

**Comment by konarshankar07** [comment]
Hello @sivaschenko ....
If we change the order of column then the position of the overlay will going to change . Sorry, I'm not able to understand properly

**Comment by sivaschenko** [comment]
Hi @konarshankar07 that is exactly what the issue is - overlay column depends on the position in the grid. If sort order will be removed - the sequence of columns could be changed via extensions

**Comment by coderimus** [comment]
Hi @konarshankar07 ! Thank you for the provided improvements 👍  Please, update your PR's branch and resolve conflicts :)

**Comment by coderimus** [comment]
@konarshankar07 please, take into account that 

> the new default branch 2.0.0-develop is for the stabilization for the upcoming release, PRs including important bugfixes should be opened towards this branch

So, I think that the target branch should be 2.0.0-develop. Please, change :)

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Comment by konarshankar07** [comment]
Hello @sivaschenko or @lenaorobei ...
How can I reopen this issue?
Thanks

**Comment by lenaorobei** [comment]
Sure. Reopened this PR.

**Comment by konarshankar07** [comment]
@magento run all tests

**Comment by konarshankar07** [comment]
Hello @chalov-anton ....
In Custom masonary gallery,
image

In Adobe Stock Media Gallery,
image

Please test and let me know if you have any questions
Thanks

**Comment by konarshankar07** [comment]
@magento run Functional Tests EE

**Review by chalov-anton — COMMENTED** [review]
Hello @konarshankar07 
This is the result I get on, for example, **Catalog - Categories - Content -  Select from Gallery** page even without changing the column order 
catcat

**Comment by konarshankar07** [comment]
Hello @chalov-anton ...
I'm not able to reproduce the issue with you have mentioned. Please check the below screenshot
image
Have you checkout the https://github.com/magento/magento2/pull/27981 PR in the Magento repo?
Thanks

**Comment by chalov-anton** [comment]
Hello @konarshankar07 

I have switched Magento2 to the https://github.com/magento/magento2/pull/27981 PR and ASI to https://github.com/magento/adobe-stock-integration/pull/1134 PR.
I did not change anything in the code, did not change the position of the _column_ in _media_gallery_listing.xml_.
I open Media Gallery form Catalog - Categories, and this is the result I get 
overlay

**Comment by sivaschenko** [comment]
Looks like the desired behaviour is not achievable with the current approach: closing PRs and the task

**Pull request closed without merging**
