### PR TITLE
#398: "See more" link applies Series filter to the grid

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will fix the issue or enhance following functionality
1) Loader added when series ajax request initiated
2) See more link added in the series image list and initiate filter based on current serie_id
3) Fixed issue with a view all keyword as the user is not able to view all the keyword when user click on view all button in the last image in the grid

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#398: "See more" link applies Series filter to the grid

### Manual testing scenarios (*)

1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Click on filter button
5. Series id filter is not visible
6. Click on any image
7. User sees the see more link
8. On clicking "see more", serie_id filter is initiated

### CODE REVIEW

**Comment by sivaschenko** [comment]
This pull request depends on https://github.com/magento/adobe-stock-integration/pull/408 - template should be adjuster after the previous PR merge

**Review by sivaschenko — APPROVED** [review]

**Review by sivaschenko — CHANGES_REQUESTED** [review]
@konarshankar07 Thanks for the pull request!

There is an improvement that can be done to UX of this filter:
Currently, the applied Series filter is not reflected in the interface and there is no way to clear that filter. Do you think this functionality can be added to the implementation?

It would be good to see Series filter applied (in the section of applied filters) while keeping the actual input for this filter hidden.

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
I will try to improve the UX so that user can clear the filter.
Thanks

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
I have added series id filter in the active filter list. Please check and let me know if you want to make any changes
Thanks

**Comment by sivaschenko** [comment]
Hi @konarshankar07 thanks for updates! There is an issue with the serie filter:

Steps to Reproduce:
1. Apply serie filter (by clicking "See more" link in the image preview)
2. Reload the page and reopen the Adobe Stock images grid

Actual Result:
Serie filter is applied, but gird is not filtered by serie

Expected Result:
Serie filter is applied and the grid is filtered by serie

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
