### PR TITLE
#144 : Set correct filters order on the grid

### PR DESCRIPTION
**Pull request by konarshankar07**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#144 : Set correct filters order on the grid
2. ...

### Manual testing scenarios (*)

Correct Filter order:
1. Subcategory filter
2. Orientation filter
3. Color filter
4. Price filter
5. Safe search filter
6. Isolated Assets filter

image

### CODE REVIEW

**Review by diazwatson — CHANGES_REQUESTED** [review]
Hi @konarshankar07 thanks for your contribution
Few small changes in here:

- Make sure you sign the license agreement
- Add sort order to each filter (10,20,30) following the order specified in the ticket description.

For example:
```
<filterSelect name="content_type_filter" provider="${ $.parentName }" sortOrder="10">
```
```
<filterSelect name="orientation_filter" provider="${ $.parentName }" sortOrder="20">
```
Please let me know if you have any doubt.

**Comment by konarshankar07** [comment]
hello @diazwatson ,
I'll add the sort order in the each filter and regarding signing the license agreement, i'm getting the following image 
image

**Comment by diazwatson** [comment]
Hi @konarshankar07 
Yes, just click on the `license/cla` and accept the terms and conditions.

Please let me know if you have any problem

**Comment by konarshankar07** [comment]
Hello @diazwatson ,
`license/cla` doesn't have link. Please check the below screenshot. I've already accepted the license agreement about 10 to 12 days ago

image

**Comment by konarshankar07** [comment]
@diazwatson ,

I managed to accept the license and also finished the changes that you mentioned.

Thanks

**Review by diazwatson — APPROVED** [review]

**Comment by diazwatson** [comment]
Thanks @konarshankar07 your PR is now merged 👍

**Pull request merged**
