### PR TITLE
[Stub] Provide save asset file support

### PR DESCRIPTION
**Pull request by coderimus**
### Description (*)
This PR provides the save image emulation. This achieved by using the `Magento\Framework\Filesystem\Driver\File` functionality instead of the `Magento\Framework\Filesystem\Driver\HTTPS`.

### Fixed Issues (if relevant)
#1544 

### Manual testing scenarios (*)
N/A

### CODE REVIEW

**Comment by coderimus** [comment]
@magento run all tests

**Comment by coderimus** [comment]
@magento run all tests

**Comment by coderimus** [comment]
@magento run all tests

**Comment by coderimus** [comment]
@magento run all tests

**Comment by coderimus** [comment]
@magento run all tests

**Comment by coderimus** [comment]
Hi @sivaschenko , may I ask you to help with the investigation of the failed results of functions tests? I could not reproduce them locally: I can save an image successfully and open Adobe STock Search panel without any errors. My local setup is PHP 7.4, Magento 2.4.

**Comment by sivaschenko** [comment]
@coderimus I believe the issue you are experiencing is related to SSL validation, in this case I think the only things we should do to resolve this issue for dev environments is to change `Https` to `DriverInterface` depency in the `Magento\AdobeStockImage\Model\Storage\Save` constructor and add DI configuration to provide `Http` driver instead of `Https` to `Magento\AdobeStockImage\Model\Storage\Save`. I don't think any additional changes are necessary

**Comment by sivaschenko** [comment]
@coderimus closing this pull request as there is no capacity currently to work on the stub implementation and it is currently out of priority. Feel free to reopen the PR if/when you'd like to continue working on it

**Pull request closed without merging**
